apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
  labels:
    type: {{ .Release.Name }}-ssh
spec:
  type: NodePort
  ports:
  - name: sftp
    port: 22
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-ssh