apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    proxy: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: LoadBalancer
