apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}
  annotations:
    {{- if .Values.network }}
    {{- if .Values.network.domainName }}
    #Integration option for external dns
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.network.domainName }}
    #Integration option for mc-router
    mc-router.itzg.me/externalServerName: {{ .Values.network.domainName }}
    {{- else }}
    #Integration option for external dns
    external-dns.alpha.kubernetes.io/hostname: {{.Release.Name}}.{{.Release.Namespace}}.mcsh.red
    #Integration option for mc-router
    mc-router.itzg.me/externalServerName: {{.Release.Name}}.{{.Release.Namespace}}.mcsh.red
    {{- end }}
    {{- end }}
  labels:
    type:  {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
  selector:
    app:  {{ .Release.Name }}
