ingress:
  class: nginx
  host: foo.bar.com
  clusterIssuer: #If empty no cert manager annotation is added
panel:
  image: registry.service.mcserverhosting.net/library/panel:latest
  storageClassName: nvme-replicated
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
kuber:
  image: registry.service.mcserverhosting.net/library/kuber:latest
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
#Dependencies below
mariadb:
  global:
    storageClass: nvme-replicated
  #citing https://github.com/kubectyl/panel/blob/develop/docker-compose.example.yml
  auth:
    database: panel
    username: pterodactyl
    password: CHANGE_ME
    rootPassword: CHANGE_ME_TOO
  secondary:
    replicaCount: 0
redis:
  global:
    storageClass: nvme-replicated
  auth:
    enabled: false
  replica:
    replicaCount: 0
  sentinel:
    enabled: false


