apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcshadmin
subjects:
- kind: User
  name: {{ .Values.user }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: mcshadmin
  apiGroup: rbac.authorization.k8s.io
