apiVersion: mcserverhosting.net/v2
kind: MinecraftServer
metadata:
  name: play
  namespace: {{.Release.Name}}
  annotations:
    helm.sh/hook: post-install
spec:
  java:
    argsdd: fml.queryResult:confirm
    argsxx: -XX:+UseLargePagesInMetaspace -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions
      -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50
      -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch
      -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseLargePages
      -XX:LargePageSizeInBytes=2m
  minecraft:
    eula: true
    memory:
      initial: 1G
      max: 1800M
    version: LATEST
  online: true
  overrideOnStartup: false
  servercore:
    type: VANILLA
