apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ns-pvc
  namespace: {{.Release.Name}}
spec:
  storageClassName: longhorn-hhd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ mul (trimSuffix "GB" .Values.plan) 10 }}Gi