apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcshadmin
  namespace: {{.Values.namespace}}
subjects:
- kind: User
  name: {{ .Values.email }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: mcshadmin
  apiGroup: rbac.authorization.k8s.io
