apiVersion: v1
kind: ConfigMap
metadata:
  name: webdav
  namespace: {{.Release.Name}}
data:
  config.yaml: |
    address: 0.0.0.0
    port: 8080
    auth: true
    tls: false
    prefix: /

    # Default user settings (will be merged)
    scope: /home/admin
    modify: true
    rules: []

    users:
      - username: admin
        password: "{env}ENV_PASSWORD"
        scope: /home/admin