apiVersion: v2
name: sftp-deployment
version: 2.0
kubeVersion: < 1.15.0
description: An SFTP deployment deployment for MCSH. Includes user management for keys and uid.
type: application
keywords:
  - mcserverhosting
  - sftp
  - ftp
  - user
home: https://mcserverhosting.net/
sources:
  - https://github.com/mcserverhosting-net/charts
maintainers:
  - name: sfxworks
    email: sfxworks@gmail.com
    url: sfxworks.net
icon: https://avatars0.githubusercontent.com/u/49386422
appVersion: 2.0
deprecated: false