apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-filesystem
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.1.1.1
      - 1.0.0.1
  nodeSelector:
    core: i7
  containers:
    - name: filesystem-interface
      image: busybox
      volumeMounts:
        - name: filesystem
          mountPath: /mnt/filesystem
      workingDir: /mnt/filesystem
      command:
        - sleep
        - "36000"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volumes:
    - name: filesystem
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-pv-claim