apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  {{- if eq .Values.type "POSTGRES" }}
  - port: 5432
    name: database
  {{- else }}
  - port: 3306
    name: database
  {{- end }}
  selector:
    app: {{ .Release.Name }}
