apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Release.Name }}
        {{- with .Values }}
        {{- if eq .type "MYSQL" }}
        image: mysql:{{ .version }}
        ports:
        - containerPort: 3306
          name: database
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
          subPath: database/{{ $.Release.Name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .password }}
        {{- else if eq .type "MARIADB" }}
        image: mariadb:{{ .version }}
        ports:
        - containerPort: 3306
          name: database
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
          subPath: database/{{ $.Release.Name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .password }}
        {{- else if eq .type "POSTGRES" }}
        image: postgres:{{ .version }}
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: database
          mountPath: /var/lib/postgresql/data
          subPath: database/{{ $.Release.Name }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .password }}
        {{- end }}
        {{- end }}
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: ns-pvc
          readOnly: false
