{{- if .Values.network.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-extra-ports
  labels:
    type: {{ .Release.Name }}-extra-ports
spec:
  type: NodePort
  ports:
  {{- range .Values.network.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app:  {{ .Release.Name }}
{{- end }}