apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-external
  annotations:
    {{- if .Values.network }}
    {{- if .Values.network.domainName }}
    #Integration option for external dns
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.network.domainName }}
    {{- else }}
    #Integration option for external dns
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{ .Release.Namespace }}.mcsh.io
    {{- end }}
    {{- end }}
  labels:
    type:  {{ .Release.Name }}
spec:
  type: ExternalName
  {{- if .Values.ip }}
  externalName: {{ .Values.ip }}
  {{- end }}