apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Release.Name }} 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: panel
        image: ghcr.io/pterodactyl/panel:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: panel
          mountPath: /app/var/
          subPath: var
        - name: panel
          mountPath: /etc/nginx/http.d/
          subPath: nginx
        - name: panel
          mountPath: /app/storage/logs/
          subPath: logs
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 20Gi
