apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ns-pvc
spec:
  storageClassName: {{ .Values.storageclass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}