apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    services.nodeports: {{ .Values.ports }}
    count/sftpservers.mcserverhosting.net: {{ .Values.servers.sftp }}
    count/minecraftservers.mcserverhosting.net: {{ .Values.servers.minecraft }}
    count/bungeedeployments.mcserverhosting.net: {{ .Values.servers.bungee }}
    count/database.mcserverhosting.net: {{ .Values.servers.database }}
    limits.memory: {{ .Values.memory }}
    hugepages-2Mi: {{ .Values.hugePages2mi }}
