apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-restic-init"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: restic-init
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: restic-init
        image: restic/restic
        args:
        - -c
        - restic init
        command:
        - /bin/sh
        envFrom:
        - secretRef:
          name: {{ .Release.Name }}-backup
