apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - -c
            - restic unlock && restic --exclude="*.zip" -vvvvv backup /userdata --no-cache
              && restic forget --keep-last 120 --prune && restic snapshots
            command:
            - /bin/sh
            envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backup
            image: restic/restic
            name: backup
            resources:
              limits:
                cpu: "250m"
                memory: 512Mi
              requests:
                cpu: "250m"
                memory: 512Mi
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - mountPath: /userdata
              name: minecraft-volume
          volumes:
          - name: userdata
            persistentVolumeClaim:
              claimName: ns-pvc
              readOnly: false
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false