apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup
stringData:
  RESTIC_REPOSITORY: {{ .Values.repository }}/{{ .Release.Namespace }} 
  RESTIC_PASSWORD: {{ .Values.password }}
  AWS_ACCESS_KEY_ID: {{ .Values.id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.key }}