apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-proxy
spec:
  serviceName: {{ .Release.Name }}-proxy
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy
  {{- if .Values.online }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy
    spec:
      {{- if .Values.runtime }}
      runtimeClassName: {{ .Values.admin.runtime }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 999
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Release.Name }}
        tty: true
        stdin: true
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 15
          periodSeconds: 4
          failureThreshold: 300
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        {{- if .Values.javaOverride }}
        image: docker.io/itzg/bungeecord:java{{.Values.javaOverride}}
        {{- end }}
        env:
        {{- if .Values.jar }}
        - name: BUNGEE_JAR 
          value: {{ .Values.jarName }}
        - name: BUNGEE_JAR_URL
          value: {{ .Values.jar }}
        {{- end }}
        {{- if .Values.plugins }}
        - name: PLUGINS
          value: {{ include "helm-toolkit.utils.joinListWithComma" .Values.plugins }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
          limits:
            memory: {{ .Values.config.memory.max }}i
            cpu: 1
          requests:
            memory: {{ .Values.config.memory.initial }}i
            cpu: 100m
        ports:
        - containerPort: 25565
          name: proxy
        {{- range .Values.config.network.ports }}
        - containerPort: {{ .port }}
          name: {{ .name }}
          protocol: {{ .protocol }}
        {{- end }}
        volumeMounts:
        - name: proxy-volume
          mountPath: /server
          subPath: proxy/{{ .Release.Name }}
      restartPolicy: Always
      volumes:
      - name: proxy-config
        configMap:
          name: {{ .Release.Name }}-proxy-config
      - name: proxy-volume
        persistentVolumeClaim:
          claimName: ns-pvc
          readOnly: false
