apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
data:
  RESTIC_PASSWORD: {{ randAlphaNum 30 | b64enc}}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc}}