apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-server
  labels:
    type:  {{ .Release.Name }}-server
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: rcon
    port: 25575
    protocol: TCP
    targetPort: 25575
  - name: extra
    port: 25567
    targetPort: 25567
  selector:
    app:  {{ .Release.Name }}-server