{{- range $key, $val := .Values.servers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  EULA: {{ default false .eula | quote }}
  VERSION: {{ .version | default "LATEST" | quote }}
  {{- if .type }}
  TYPE: {{ .type | quote }}
  {{- if eq .type "FORGE" }}
  {{- if .forge }}
  {{- if .forge.version }}FORGEVERSION: {{ .forge.version }}{{ end }}
  {{- if .forge.installer }}FORGE_INSTALLER: {{ .forge.installer }}{{ end }}
  {{- if .forge.url }}FORGE_INSTALLER_URL: {{ .forge.url }}{{ end }}
  {{- end }}
  {{- end }}
  {{- if eq .type "BUKKIT" }}
  {{- if .bukkit }}
  {{- if .bukkit.url }}BUKKIT_DOWNLOAD_URL: {{ .bukkit.url }}{{ end }}
  {{- end }}
  {{- end }}
  {{- if eq .type "SPIGOT" }}
  {{- if .spigot.url }}SPIGOT_DOWNLOAD_URL: {{ .spigot.url }}{{ end }}
  BUILD_FROM_SOURCE: {{ default false .spigot.build | quote }}
  {{- end }}
  {{- if .curseforge }}
  {{- if eq .type "CURSEFORGE" }}
  CF_SERVER_MOD: {{ .curseforge.modpack.url }}
  {{- end }}
  {{- end }}
  {{- if .ftb }}
  {{- if eq .type "FTB" }}
  FTB_SERVER_MOD: {{ .ftb.modpack.url }}
  FTB_LEGACYJAVAFIXER: {{ default false .ftb.modpack.legacy | quote }}
  {{- end }}
  {{- end }}
  {{- if .spongevanilla }}
  {{- if eq .type "SPONGEVANILLA" }}
  SPONGEVERSION: {{ .spongevanilla.version | default "STABLE" }}
  {{- if .spongevanilla.branch }}SPONGEBRANCH: {{ .spongevanilla.branch }}{{ end }}
  {{- end }}
  {{- end }}
  {{- if .fabric }}
  {{- if eq .type "FABRIC" }}
  {{- if .fabric.version }}FABRICVERSION: {{ .fabric.version }}{{ end }}
  {{- if .fabric.installer }}FABRIC_INSTALLER: {{ .fabric.installer }}{{ end }}
  {{- if .fabric.url }}FABRIC_INSTALLER_URL: {{ .fabric.url }}{{ end }}
  {{- end }}
  {{- end }}
  {{- if .custom }}
  {{- if eq .type "CUSTOM" }}
  CUSTOM_SERVER: {{ .custom.url }}
  {{- end }}
  {{- end }}
  {{- end }}
  FORCE_REDOWNLOAD: {{ default false .forceRedownload | quote }}
  OVERRIDE_SERVER_PROPERTIES: {{ default true .overrideOnStartup | quote }}
  SERVER_NAME: {{ .name }}
  {{- with .config }}
  ICON: {{ default "https://firebasestorage.googleapis.com/v0/b/mchostingnet-202204.appspot.com/o/mcshicon.png?alt=media&token=efcba97b-9a5d-4e62-a3bb-39a3b36b2ff7" .icon }}
  {{- if .modpack }}MODPACK: {{ .modpack }} {{ end }}
  MOTD: {{ default "Your new MCSH minecraft server!" .motd }}
  {{- if .mods }}MODS: {{ .mods }} {{ end }}
  REMOVE_OLD_MODS: {{ default true .removeOldMods | quote }}
  JVM_DD_OPTS: fml.queryResult:confirm
  CONSOLE: {{ default true .console | quote }}
  GUI: "false"
  INIT_MEMORY: {{ .memory.initial | default "1Gi" }}
  MAX_MEMORY: {{ .memory.max | default "1Gi" }}
  {{- end }}
  {{- with .server }}
  {{- if .network.rcon.enabled }}
  ENABLE_RCON: true
  {{- if .network.rcon.password }}
  RCON_PASSWORD: {{ .network.rcon.password}}
  {{- else }}
  RCON_PASSWORD: {{ randAlphaNum 20 }}
  {{- end }}
  {{- end }}
  OPS: {{ .restrictions.ops | default "sfxworks" }}
  ENABLE_QUERY: {{ default true .network.query | quote }}
  MAX_PLAYERS: {{ default "2020" .network.maxPlayers }}
  ALLOW_NETHER:  {{ default true .gameSettings.nether | quote }}
  DIFFICULTY: {{ .gameSettings.difficulty | default "hard" }}
  ANNOUNCE_PLAYER_ACHIEVEMENTS:  {{ default true .gameSettings.announcePlayerAchievements | quote }}
  ENABLE_COMMAND_BLOCK: {{ default true .gameSettings.commandBlocks | quote }}
  FORCE_GAMEMODE: {{ default false .restrictions.forceGamemode | quote }}
  HARDCORE: {{ default true .gameSettings.hardcore | quote }}
  SNOOPER_ENABLED: {{ default true .gameSettings.snooper | quote }}
  MAX_TICK_TIME: {{ .maxTickTime | default "20000" }}
  PVP: {{ default true .gameSettings.pvp | quote }}
  ONLINE_MODE: {{ default true .network.onlineMode | quote }}
  {{- if .restrictions.whitelist }}WHITELIST: {{ .restrictions.whitelist }}{{ end }}
  {{- end }}
  {{- with .world }}
  {{- if .restrictions.maxSize }}MAX_WORLD_SIZE: {{ .restrictions.maxSize }} {{ end }}
  MAX_BUILD_HEIGHT: {{ .restrictions.maxBuildHeight | default "256" }}
  GENERATE_STRUCTURES: {{ default true .generateStructures | quote }}
  SPAWN_ANIMALS: {{ default true .spawnAnimals | quote }}
  SPAWN_NPCS: {{ default true .spawnNpcs | quote }}
  SPAWN_PROTECTION: {{ default true .restrictions.spawnProtection | quote }}
  {{- if .restrictions.viewDistance }}VIEW_DISTANCE: {{ .restrictions.viewDistance }} {{ end }}
  {{- if .seed }}SEED: {{ .seed }}{{ end }}
  MODE: {{ .mode | default "Survival"}}
  LEVEL_TYPE: {{ .level | default "DEFAULT"}}
  LEVEL: {{ .name | default "mcshworld" }}
  {{- if .url }}WORLD: {{ .url }}{{ end }}
  {{- end }}
{{- end }}