apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  replicas: 1
  template:
    metadata:
      name: {{ .Release.Name }}-server
      labels:
        app: {{ .Release.Name }}-server
    spec:
      nodeSelector:
        core: i7
      containers:
      - name: ssh
        env:
        - name: ROOT_PASSWORD
          value: {{ randAlphaNum 20 }}
        image: docker.io/mobilecommercelab/sshd-password
        imagePullPolicy: Always
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: minecraft-volume
      - name: mc-server
        image: docker.io/itzg/minecraft-server
        tty: true
        stdin: true
        env:
        - name: EULA
          value: "{{ .Values.minecraft.config.eula }}"
        - name: ICON
          value: {{ .Values.minecraft.config.icon }}
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          value: {{ .Values.minecraft.properties.rconPassword }}
        - name: MAX_PLAYERS
          value: "{{ .Values.minecraft.properties.players }}"
        - name: SERVER_NAME
          value: {{ .Release.Name }}
        - name: MOTD
          value: {{ .Values.minecraft.properties.motd }}
        - name: INIT_MEMORY
          value: {{ .Values.memoryRequest }}G
        - name: MAX_MEMORY
          value: {{ .Values.memoryBurst }}G
        - name: TYPE
          value: {{ .Values.minecraft.type }}
        - name: VERSION
          value: {{ .Values.minecraft.version }}
        - name: MODE
          value: {{ .Values.minecraft.properties.mode }}
        - name: OPS
          value: {{ .Values.minecraft.config.ops }}
        {{if eq .Values.minecraft.version "FORGE"}}
        - name: FORGEVERSION
          value: {{ .Values.minecraft.forge.version }}
        {{end}}
        resources:
          limits:
            memory: {{ .Values.memoryBurst }}Gi
          requests:
            cpu: 250m
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
        volumeMounts:
        - name: minecraft-volume
          mountPath: /data
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
      restartPolicy: Always