{{- range $key, $val := .Values.servers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  EULA: {{ .eula | default "false" | quote }}
  VERSION: {{ .version | default "LATEST" | quote }}
  {{- if .type }}
  TYPE: {{ .type | quote }}
  {{- if eq .type "FORGE" }}
  {{- if .forge.version }}FORGEVERSION: {{ .forge.version }}{{ end }}
  {{- if .forge.installer }}FORGE_INSTALLER: {{ .forge.installer }}{{ end }}
  {{- if .forge.url }}FORGE_INSTALLER_URL: {{ .forge.url }}{{ end }}
  {{- end }}
  {{- if eq .type "BUKKIT" }}
  {{- if .bukkit.url }}BUKKIT_DOWNLOAD_URL: {{ .bukkit.url }}{{ end }}
  {{- end }}
  {{- if eq .type "SPIGOT" }}
  {{- if .bukkit.url }}SPIGOT_DOWNLOAD_URL: {{ .spigot.url }}{{ end }}
  BUILD_FROM_SOURCE: {{ .spigot.build | default false }}
  {{- end }}
  {{- if eq .type "CURSEFORGE" }}
  CF_SERVER_MOD: {{ .curseforge.modpack.url }}
  {{- end }}
  {{- if eq .type "FTB" }}
  FTB_SERVER_MOD: {{ .ftb.modpack.url }}
  FTB_LEGACYJAVAFIXER: {{ .ftb.modpack.legacy | quote | default "false" }}
  {{- end }}
  {{- if eq .type "SPONGEVANILLA" }}
  SPONGEVERSION: {{ .spongevanilla.version | default "STABLE" }}
  {{- if .spongevanilla.branch }}SPONGEBRANCH: {{ .spongevanilla.branch }}{{ end }}
  {{- end }}
  {{- if eq .type "FABRIC" }}
  {{- if .fabric.version }}FABRICVERSION: {{ .fabric.version }}{{ end }}
  {{- if .fabric.installer }}FABRIC_INSTALLER: {{ .fabric.installer }}{{ end }}
  {{- if .fabric.url }}FABRIC_INSTALLER_URL: {{ .fabric.url }}{{ end }}
  {{- end }}
  {{- if eq .type "CUSTOM" }}
  CUSTOM_SERVER: {{ .custom.url }}
  {{- end }}
  {{- end }}
  FORCE_REDOWNLOAD: {{ .forceRedownload | quote | default false }}
  OVERRIDE_SERVER_PROPERTIES: {{ .overrideOnStartup | quote | default "true"}}
  SERVER_NAME: {{ .name }}
  {{- with .config }}
  ICON: {{ .icon | default "https://firebasestorage.googleapis.com/v0/b/mchostingnet-202204.appspot.com/o/mcshicon.png?alt=media&token=efcba97b-9a5d-4e62-a3bb-39a3b36b2ff7" }}
  {{- if .modpack }}MODPACK: {{ .modpack }} {{ end }}
  MOTD: {{ .motd | default "Your new MCSH minecraft server!" }}
  {{- if .mods }}MODS: {{ .mods }} {{ end }}
  REMOVE_OLD_MODS: {{ .removeOldMods | quote | default true }}
  JVM_DD_OPTS: fml.queryResult:confirm
  CONSOLE: {{ .console | quote | default true }}
  GUI: "false"
  INIT_MEMORY: {{ .memory.initial | default "1Gi" }}
  MAX_MEMORY: {{ .memory.max | default "1Gi" }}
  {{- end }}
  {{- with .server }}
  {{- if .network.rcon.enabled }}
  ENABLE_RCON: true
  {{- if .network.rcon.password }}
  RCON_PASSWORD: {{ .network.rcon.password}}
  {{- else }}
  RCON_PASSWORD: {{ randAlphaNum 20 }}
  {{- end }}
  {{- end }}
  OPS: {{ .restrictions.ops | default "sfxworks" }}
  ENABLE_QUERY: {{ .network.query | default "true" }}
  MAX_PLAYERS: {{ .network.maxPlayers | default "2020" }}
  ALLOW_NETHER:  {{ .gameSettings.nether | quote | default true }}
  DIFFICULTY: {{ .gameSettings.difficulty | default "hard" }}
  ANNOUNCE_PLAYER_ACHIEVEMENTS:  {{ .gameSettings.announcePlayerAchievements | default true }}
  ENABLE_COMMAND_BLOCK: {{ .gameSettings.commandBlocks | quote | default true }}
  FORCE_GAMEMODE: {{ .restrictions.forceGamemode | quote | default false }}
  HARDCORE: {{ .gameSettings.hardcore | quote | default true }}
  SNOOPER_ENABLED: {{ .gameSettings.snooper | quote | default true }}
  MAX_TICK_TIME: {{ .maxTickTime | default "20000" }}
  PVP: {{ .gameSettings.pvp | quote | default true }}
  ONLINE_MODE: {{ .network.onlineMode | quote | default true }}
  {{- if .restrictions.whitelist }}WHITELIST: {{ .restrictions.whitelist }}{{ end }}
  {{- end }}
  {{- with .world }}
  {{- if .restrictions.maxSize }}MAX_WORLD_SIZE: {{ .restrictions.maxSize }} {{ end }}
  MAX_BUILD_HEIGHT: {{ .restrictions.maxBuildHeight | default "256" }}
  GENERATE_STRUCTURES: {{ .generateStructures | quote | default true }}
  SPAWN_ANIMALS: {{ .spawnAnimals | quote | default true }}
  SPAWN_NPCS: {{ .spawnNpcs | quote | default true }}
  SPAWN_PROTECTION: {{ .restrictions.spawnProtection | quote | default true }}
  {{- if .restrictions.viewDistance }}VIEW_DISTANCE: {{ .restrictions.viewDistance }} {{ end }}
  {{- if .seed }}SEED: {{ .seed }}{{ end }}
  MODE: {{ .mode | default "Survival"}}
  LEVEL_TYPE: {{ .level | default "DEFAULT"}}
  LEVEL: {{ .name | default "mcshworld" }}
  {{- if .url }}WORLD: {{ .url }}{{ end }}
  {{- end }}
{{- end }}