apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  {{- if .Values.online }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.runtime }}
      runtimeClassName: {{ .Values.runtime }}
      {{- end }}
      securityContext:
        runAsUser: {{ default .Values.userID 1000 }} 
        runAsGroup: {{ default .Values.groupID 999 }} 
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/game: ""
      containers:
      - name: {{ .Release.Name }}
        securityContext:
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        startupProbe:
          tcpSocket:
            port: minecraft
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: minecraft
          periodSeconds: 10
          failureThreshold: 1
        livenessProbe:
          tcpSocket:
            port: minecraft
          periodSeconds: 10
          failureThreshold: 1
        {{- if .Values.servercore.type }}
        {{- if eq .Values.servercore.type "VANILLA" }}
        image: docker.io/itzg/minecraft-server:adopt13
        {{- else }}
        image: docker.io/itzg/minecraft-server:latest
        {{- end }}
        {{- end }}
        tty: true
        stdin: true
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
          limits:
            memory: {{ .Values.minecraft.memory.max }}i
            {{- if .Values.pages }}
            hugepages-2Mi: {{ .Values.minecraft.memory.hugePages }}i
            {{- end }}
          requests:
            memory: {{ .Values.minecraft.memory.initial }}i
            cpu: 100m
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: minecraft-volume
          mountPath: /data
          subPath: servers/{{ .Release.Name }}
        - name: minecraft-volume
          mountPath: /web
          subPath: web
      restartPolicy: Always
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: ns-pvc
          readOnly: false
      {{- if .Values.pages }}
      - name: hugepage-2mi
        emptyDir:
          medium: HugePages-2Mi
      {{- end }}