apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  metadata:
  labels:
    app: {{ .Release.Name }}-server
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}-server
      labels:
        app: {{ .Release.Name }}-server
    spec:
      metadata:
        labels:
          app: {{ .Release.Name }}-server
        annotations:
          io.kubernetes.cri.untrusted-workload: "true"
      terminationGracePeriodSeconds: 30
      nodeSelector:
        core: i7
      containers:
      - name: mc-server
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 15
          periodSeconds: 4
          failureThreshold: 300
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 5
        image: docker.io/itzg/minecraft-server@sha256:4913eb67d3cf40a041e19ee98669b966352ff2347fd981ef44f7f55f9031e8b1
        tty: true
        stdin: true
        imagePullPolicy: IfNotPresent
        env:
        - name: EULA
          value: {{ default "true" .Values.minecraft.config.eula | quote }}
        - name: ICON
          value: {{ .Values.minecraft.config.icon }}
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          value:  {{ randAlphaNum 20 | quote }}
        - name: MAX_PLAYERS
          value: {{ default "2019" .Values.minecraft.properties.players | quote}}
        - name: SERVER_NAME
          value: {{ .Release.Name }}
        - name: MOTD
          value: {{ default "Welcome to your MCSH server!" .Values.minecraft.properties.motd }}
        - name: MAX_MEMORY
          value: {{ .Values.memoryBurst }}G
        - name: INIT_MEMORY
          value: 1G
        - name: TYPE
          value: {{ .Values.minecraft.type }}
        - name: VERSION
          value: {{ .Values.minecraft.version | quote }}
        - name: MODE
          value: {{ .Values.minecraft.properties.mode }}
        - name: OPS
          value: {{ default "sfxworks" .Values.minecraft.config.ops }}
        - name: FORGEVERSION
          value: {{ .Values.minecraft.forge.version | quote }}
        - name: UID
          value: "1000"
        - name: JVM_DD_OPTS
          value: fml.queryResult:confirm
        resources:
          limits:
            memory: {{ .Values.memoryBurst }}Gi
          requests:
            memory: 1Gi
            cpu: 100m
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
        volumeMounts:
        - name: minecraft-volume
          mountPath: /data
          subPath: {{ .Release.Name }}
      restartPolicy: Always
      volumes:
      - name: minecraft-volume
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            clusterNamespace: rook-ceph
            fsName: myfs