apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  {{- if .Values.online }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Release.Name }}
        securityContext:
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 15
          periodSeconds: 4
          failureThreshold: 300
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        {{- if .type }}
        {{- if eq .type "SPONGEVANILLA" }}
        image: docker.io/itzg/minecraft-server:latest
        {{- else if eq .type "FORGE"  }}
        image: docker.io/itzg/minecraft-server:latest
        {{- else }}
        image: docker.io/itzg/minecraft-server:adopt13
        {{- end }}
        {{- else }}
        image: docker.io/itzg/minecraft-server:adopt13
        {{- end }}
        tty: true
        stdin: true
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: {{ .Values.config.memory.max }}i
          requests:
            memory: {{ .Values.config.memory.initial }}i
            cpu: 100m
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
        volumeMounts:
        - name: minecraft-volume
          mountPath: /data
          subPath: {{ .Release.Namespace }}/{{ .Release.Name }}
      restartPolicy: Always
      volumes:
      - name: minecraft-volume
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            clusterNamespace: rook-ceph
            fsName: myfs