apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  metadata:
  labels:
    app: {{ .Release.Name }}-server
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}-server
      labels:
        app: {{ .Release.Name }}-server
    spec:
      metadata:
        labels:
          app: {{ .Release.Name }}-server
        annotations:
          io.kubernetes.cri.untrusted-workload: "true"
      terminationGracePeriodSeconds: 30
      nodeSelector:
        core: i7
      containers:
      - name: mc-server
        readinessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - status
          initialDelaySeconds: 15
          periodSeconds: 4
          failureThreshold: 30
        livenessProbe:
          exec:
            command:
            - mcstatus
            - localhost
            - status
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 5
        image: docker.io/itzg/minecraft-server@sha256:2311d6ff128df8081f3ab663ea262fda7f53f96a13b251f4d2486fa1921ad342
        tty: true
        stdin: true
        imagePullPolicy: IfNotPresent
        env:
        - name: EULA
          value: {{ default "true" .Values.minecraft.config.eula | quote }}
        - name: ICON
          value: {{ .Values.minecraft.config.icon }}
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          value:  {{ randAlphaNum 20 | quote }}
        - name: MAX_PLAYERS
          value: {{ default "2019" .Values.minecraft.properties.players | quote}}
        - name: SERVER_NAME
          value: {{ .Release.Name }}
        - name: MOTD
          value: {{ default "Welcome to your MCSH server!" .Values.minecraft.properties.motd }}
        - name: MAX_MEMORY
          value: {{ .Values.memoryBurst }}G
        - name: TYPE
          value: {{ .Values.minecraft.type }}
        - name: VERSION
          value: {{ .Values.minecraft.version | quote }}
        - name: MODE
          value: {{ .Values.minecraft.properties.mode }}
        - name: OPS
          value: {{ default "sfxworks" .Values.minecraft.config.ops }}
        - name: FORGEVERSION
          value: {{ .Values.minecraft.forge.version | quote }}
        - name: UID
          value: "1000"
        #- name: MODS
        #  value: https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2825-7.1.6/spongeforge-1.12.2-2825-7.1.6.jar
        resources:
          limits:
            memory: {{ .Values.memoryBurst }}Gi
          requests:
            memory: 1Gi
            cpu: 100m
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
        volumeMounts:
        - name: minecraft-volume
          mountPath: /data
      restartPolicy: Always
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim