apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}
  labels:
    type:  {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
  - name: rcon
    port: 25575
    protocol: TCP
  selector:
    app:  {{ .Release.Name }}