apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  {{- if .Values.online }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.runtime }}
      runtimeClassName: {{ .Values.runtime }}
      {{- end }}
      securityContext:
        runAsUser: {{ default .Values.userID 1000 }} 
        runAsGroup: {{ default .Values.groupID 999 }} 
      terminationGracePeriodSeconds: 30
      nodeSelector:
        node-role.kubernetes.io/game: ""
      containers:
      - name: {{ .Release.Name }}
        securityContext:
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 15
          periodSeconds: 4
          failureThreshold: 300
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        {{- if .Values.type }}
        {{- if eq .Values.type "VANILLA" }}
        image: docker.io/itzg/minecraft-server:adopt13
        {{- else }}
        image: docker.io/itzg/minecraft-server:latest
        {{- end }}
        tty: true
        stdin: true
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
          limits:
            memory: {{ .Values.config.memory.max }}i
          requests:
            memory: {{ .Values.config.memory.initial }}i
            cpu: 100m
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: minecraft-volume
          mountPath: /data
          subPath: servers/{{ .Release.Name }}
      restartPolicy: Always
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: ns-pvc
          readOnly: false