apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ssh
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ssh
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}-ssh
      labels:
        app: {{ .Release.Name }}-ssh
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Release.Name }}-server
            topologyKey: beta.kubernetes.io/arch
      serviceAccountName: mcsh-sa
      initContainers:
      - name: generate-publickey
        image: harbor-west.sfxworks.net:30003/library/mm
        imagePullPolicy: Always
        command: ['/bin/sh']
        args: ['-c', 'ssh-keygen -y -f /root/.tmp/id-rsa > /etc/authorized_keys/mcshadmin &&
              chown 1000:1000 /etc/authorized_keys/mcshadmin ']
        volumeMounts:
        - mountPath: /root/.tmp
          name: tmp
        - mountPath: /etc/authorized_keys
          name: ssh
      containers:
      - name: ssh
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 20
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 60
          periodSeconds: 20
        image: docker.io/panubo/sshd
        env:
        - name: SSH_USERS 
          value: mcshadmin:1000:1000
        - name: MOTD 
          value: |          
                  ███╗   ███╗ ██████╗███████╗██╗  ██╗
                  ████╗ ████║██╔════╝██╔════╝██║  ██║
                  ██╔████╔██║██║     ███████╗███████║
                  ██║╚██╔╝██║██║     ╚════██║██╔══██║
                  ██║ ╚═╝ ██║╚██████╗███████║██║  ██║
                  ╚═╝     ╚═╝ ╚═════╝╚══════╝╚═╝  ╚═╝
                  Welcome to your MCSH server console
                  Enjoy the v3.0 cluster deployment!
                  Your server is in the minecraft folder
                  Questions? mcserverhosting.net/discord
        - name: GATEWAY_PORTS
          value: "true"
        resources:
          limits:
            memory: 100Mi
            cpu: 50m
          requests:
            memory: 25Mi
            cpu: 10m
        imagePullPolicy: Always
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        volumeMounts:
        - mountPath: /home/mcshadmin/minecraft
          name: minecraft-volume
          subPath: {{ .Release.Name }}
        - mountPath: /etc/authorized_keys
          name: ssh
      restartPolicy: Always
      volumes:
      - name: minecraft-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
      - name: ssh
        emptyDir: {}
      - name: tmp
        secret:
          secretName: ssh
          defaultMode: 256